### ISSUE TITLE
Remove repo with no source code

### ISSUE THREAD

**Issue by ghost** [lgibson02/GoldenKeysUSB#2]
It's a complete waste to sit and leave an empty repo like this. You should feel stupid because you are.

**Comment by lgibson02** [comment]
Hi, this project was a re-package of Microsoft's proprietary SecureBootDebug.efi program which I've coupled with a BCD file I made providing a menu to launch it. There is no source code as such. The only reason this is on GitHub is that it was the most convenient distribution method I could think of at the time I hastily put this together. I didn't take down this repo in case somebody had linked to it, I don't like breaking links.

In case you are actually just looking for a download: https://archive.org/download/windows-rt-device-tools/Tegra_Jailbreak_USB.zip
("GoldenKeysUSB" morphed into "Tegra Jailbreak USB" a while ago)

I do now notice that my "moved" link on the readme is currently not working, the gitbook was changed  I'll update this but in the mean time it should be: https://windows-rt-devices.gitbook.io/windows/tools/tegra-jailbreak-usb

Hope that helps.
